# Numpy

Numerical python


### Array Fundamentals

It is mutable

In [1]:
import numpy as np

In [2]:
# initializing an array.

arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [3]:
arr[0]

np.int64(1)

In [5]:
# updating array elements
arr[0] = 100
print(arr)

[100   2   3   4   5]


In [6]:
# replacing given elements with another particular element
arr[:3] = 22
arr

array([22, 22, 22,  4,  5])

In [10]:
type(arr)

numpy.ndarray

### Array Attributes

In [11]:
arr.ndim # dimensions of an array

1

In [14]:
arr.size # total elements in an array

5

In [15]:
arr.shape # shows total no. of elements in each dimensions

(5,)

### Create a basic array

In [20]:
# creating array of Zeros
zeros_array = np.zeros(7)
zeros_array

array([0., 0., 0., 0., 0., 0., 0.])

In [21]:
# array of one
ones_array = np.ones(6)
ones_array


array([1., 1., 1., 1., 1., 1.])

In [23]:
# creating empty array with 3 elements
empty_array = np.empty(3)
print(empty_array)

print(empty_array[0])

[3. 2. 1.]
3.000000000000002


In [26]:
# array with range of elements
# (starting, ending, step)
range_Array = np.arange(1,6,2)
range_Array

array([1, 3, 5])

In [28]:
# create an array with values that are spaced linearly in a specified interval
linearly_spaced_Array = np.linspace(2,10,5)
linearly_spaced_Array
# NOTE : here the last element is included in output array.

array([ 2.,  4.,  6.,  8., 10.])

In [32]:
# specifying datatype during array creation
custom_Array = np.arange(4,14,1, dtype = np.float64)
custom_Array

array([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.])

### Adding, removing, and sorting elements

In [42]:
import random as rd

random_Array1 = [rd.randint(10,99)for _ in range(7)]
random_Array1

[97, 69, 78, 91, 34, 91, 23]

In [43]:
# sorting an array
np.sort(random_Array1)

array([23, 34, 69, 78, 91, 91, 97])

In [44]:
random_Array2 = [rd.randint(10,99)for _ in range(5)]
random_Array2

[51, 13, 31, 62, 98]

In [47]:
np.concatenate((random_Array1,random_Array2))

array([97, 69, 78, 91, 34, 91, 23, 51, 13, 31, 62, 98])

In [54]:
new_arr1 = np.arange(10).reshape(2,5)
new_arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
new_arr2 = np.arange(10,20).reshape(2,5)
new_arr2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [58]:
concatenated_Array = np.concatenate((new_arr1,new_arr2))
concatenated_Array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [59]:
concatenated_Array.shape

(4, 5)

In [60]:
concatenated_Array.size

20

In [61]:
concatenated_Array.ndim

2

### Reshaping an Array

In [63]:
x = np.array([2,4,6,8,10,12])
print(x)
print(x.shape)
print(x.size)
print(x.ndim)

[ 2  4  6  8 10 12]
(6,)
6
1


In [66]:
y = x.reshape(3,2)
print(y)
print('\n')
print(y.shape)
print(y.size)
print(y.ndim)

[[ 2  4]
 [ 6  8]
 [10 12]]


(3, 2)
6
2


### Indexing and slicing

In [76]:
data = np.array([56, 36, 69, 27, 23, 22, 23])
data

array([56, 36, 69, 27, 23, 22, 23])

In [77]:
data[2:4]

array([69, 27])

In [79]:
data[data>100]

array([], dtype=int64)

In [80]:
data[data<50]

array([36, 27, 23, 22, 23])

In [82]:
even_entries = data[data%2==0]
even_entries

array([56, 36, 22])