# How to create an array from existing data

This section covers slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()

In [1]:
import numpy as np

In [2]:
# let’s say you have this array:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr1 = a[3:6]
arr1

array([4, 5, 6])

In [5]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [6]:
# You can stack them vertically with vstack():

vertical_arr = np.vstack((a1,a2))
vertical_arr

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [7]:
# Or stack them horizontally with hstack():
horizontal_arr = np.hstack((a1,a2))
horizontal_arr

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [12]:
# You can split an array into several smaller arrays using hsplit()
x = np.arange(1,25)
x


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [16]:
x.reshape(2,12)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [18]:
# If you wanted to split this array into three equally shaped arrays
np.hsplit(x,3)

[array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16]),
 array([17, 18, 19, 20, 21, 22, 23, 24])]

In [19]:
new_Arr = x.copy()
new_Arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])